-- V4: Add enhanced profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS college VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS degree VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS graduation_year VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS notice_period VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS certifications TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_url TEXT;